# This workflow will do a clean installation of dependencies, build the source code and upload an artifact

name: Bun ci

on:
  push:
    tags: [ "v*" ]
    branches: 
      - "actions" 
      - "main"
  workflow_dispatch:
    branches: 
      - "actions" 
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: bun-build
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: bun install
      run: bun i
    - name: bun build
      run: bun run build
    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        files: "out/*user.js"
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v4.6.1
    #   with:
    #     # Artifact name
    #     name: userscripts # optional, default is artifact
    #     # A file, directory or wildcard pattern that describes what to upload
    #     path: ./out/*user.js
    #     if-no-files-found: error
    #     retention-days: 1

