# This workflow will do a clean installation of dependencies, build the source code and upload a release
name: Release build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: bun-build
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: bun install
      run: bun i -p --no-progress
    - name: bun build
      run: bun run build
    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        allowUpdates: true
        files: "out/*user.js"
        token: ${{ secrets.TOKEN }}

